// Demo data for seeding the database
// This file provides mock data for the seed script

export const mockProjects = [
  {
    id: "proj-1",
    name: "E-Commerce Platform",
    description:
      "A full-featured online shopping platform with cart, checkout, and payment integration.",
    status: "In Progress" as const,
    techStack: ["Next.js", "PostgreSQL", "Stripe", "Tailwind CSS"],
    lastUpdated: "2026-02-15T10:30:00Z",
    features: [
      {
        id: "feat-1",
        name: "User Authentication",
        description:
          "Implement secure user registration and login with JWT tokens.",
        priority: "High" as const,
        status: "Done" as const,
        effortEstimate: "3 days",
        tasks: [
          {
            id: "task-1",
            title: "Set up auth provider",
            description: "Configure NextAuth.js with credentials provider",
            status: "Done" as const,
            dueDate: "2026-01-20T00:00:00Z",
            effortEstimate: "4 hours",
          },
          {
            id: "task-2",
            title: "Create login page",
            description: "Design and implement login/signup forms",
            status: "Done" as const,
            dueDate: "2026-01-22T00:00:00Z",
            effortEstimate: "6 hours",
          },
          {
            id: "task-3",
            title: "Add password reset flow",
            description: "Implement email-based password reset",
            status: "Done" as const,
            dueDate: "2026-01-25T00:00:00Z",
            effortEstimate: "4 hours",
          },
        ],
      },
      {
        id: "feat-2",
        name: "Product Catalog",
        description:
          "Display products with filtering, sorting, and search functionality.",
        priority: "High" as const,
        status: "In Progress" as const,
        effortEstimate: "5 days",
        tasks: [
          {
            id: "task-4",
            title: "Create product grid component",
            description: "Build responsive product display grid",
            status: "Done" as const,
            dueDate: "2026-01-28T00:00:00Z",
            effortEstimate: "6 hours",
          },
          {
            id: "task-5",
            title: "Implement category filters",
            description: "Add sidebar filters for categories, price range",
            status: "In Progress" as const,
            dueDate: "2026-02-05T00:00:00Z",
            effortEstimate: "8 hours",
          },
          {
            id: "task-6",
            title: "Add product search",
            description: "Implement full-text search with suggestions",
            status: "To Do" as const,
            dueDate: "2026-02-10T00:00:00Z",
            effortEstimate: "1 day",
          },
        ],
      },
      {
        id: "feat-3",
        name: "Shopping Cart",
        description: "Persistent cart with quantity management.",
        priority: "High" as const,
        status: "In Progress" as const,
        effortEstimate: "3 days",
        tasks: [
          {
            id: "task-7",
            title: "Cart state management",
            description: "Set up React Context for cart state",
            status: "Done" as const,
            dueDate: "2026-02-01T00:00:00Z",
            effortEstimate: "4 hours",
          },
          {
            id: "task-8",
            title: "Cart UI components",
            description: "Build cart drawer and summary components",
            status: "In Progress" as const,
            dueDate: "2026-02-08T00:00:00Z",
            effortEstimate: "8 hours",
          },
        ],
      },
      {
        id: "feat-4",
        name: "Payment Integration",
        description: "Integrate Stripe for secure checkout processing.",
        priority: "Medium" as const,
        status: "To Do" as const,
        effortEstimate: "4 days",
        tasks: [
          {
            id: "task-9",
            title: "Set up Stripe account",
            description: "Configure Stripe API keys and webhooks",
            status: "To Do" as const,
            dueDate: "2026-02-15T00:00:00Z",
            effortEstimate: "2 hours",
          },
          {
            id: "task-10",
            title: "Create checkout flow",
            description: "Build multi-step checkout process",
            status: "To Do" as const,
            dueDate: "2026-02-20T00:00:00Z",
            effortEstimate: "2 days",
          },
        ],
      },
    ],
  },
  {
    id: "proj-2",
    name: "Project Tracker App",
    description:
      "A task management application for tracking projects, features, and decisions.",
    status: "In Progress" as const,
    techStack: ["Next.js", "PostgreSQL", "Drizzle ORM", "shadcn/ui"],
    lastUpdated: "2026-02-27T09:00:00Z",
    features: [
      {
        id: "feat-5",
        name: "Dashboard View",
        description: "Overview of all projects with status summaries.",
        priority: "High" as const,
        status: "Done" as const,
        effortEstimate: "2 days",
        tasks: [
          {
            id: "task-11",
            title: "Create dashboard layout",
            description: "Build main dashboard with sidebar navigation",
            status: "Done" as const,
            dueDate: "2026-02-10T00:00:00Z",
            effortEstimate: "6 hours",
          },
          {
            id: "task-12",
            title: "Add project cards",
            description: "Display project summaries with progress indicators",
            status: "Done" as const,
            dueDate: "2026-02-12T00:00:00Z",
            effortEstimate: "8 hours",
          },
        ],
      },
      {
        id: "feat-6",
        name: "Feature Management",
        description: "CRUD operations for features within projects.",
        priority: "High" as const,
        status: "Done" as const,
        effortEstimate: "3 days",
        tasks: [
          {
            id: "task-13",
            title: "Feature list component",
            description: "Display features with priority and status badges",
            status: "Done" as const,
            dueDate: "2026-02-14T00:00:00Z",
            effortEstimate: "6 hours",
          },
          {
            id: "task-14",
            title: "Feature dialog forms",
            description: "Create/Edit modal for feature management",
            status: "Done" as const,
            dueDate: "2026-02-16T00:00:00Z",
            effortEstimate: "8 hours",
          },
        ],
      },
      {
        id: "feat-7",
        name: "Decision Tracking",
        description:
          "Record architectural decisions with pros, cons, and alternatives.",
        priority: "Medium" as const,
        status: "Done" as const,
        effortEstimate: "2 days",
        tasks: [
          {
            id: "task-15",
            title: "Decision card component",
            description: "Display decisions with expandable pros/cons",
            status: "Done" as const,
            dueDate: "2026-02-18T00:00:00Z",
            effortEstimate: "5 hours",
          },
          {
            id: "task-16",
            title: "Decision form",
            description: "Form for creating decisions with rich text",
            status: "Done" as const,
            dueDate: "2026-02-20T00:00:00Z",
            effortEstimate: "6 hours",
          },
        ],
      },
      {
        id: "feat-8",
        name: "Search Functionality",
        description: "Global search across projects, features, and tasks.",
        priority: "Medium" as const,
        status: "In Progress" as const,
        effortEstimate: "3 days",
        tasks: [
          {
            id: "task-17",
            title: "Search input component",
            description: "Command palette style search bar",
            status: "Done" as const,
            dueDate: "2026-02-22T00:00:00Z",
            effortEstimate: "4 hours",
          },
          {
            id: "task-18",
            title: "Search results display",
            description: "Show categorized results with highlighting",
            status: "In Progress" as const,
            dueDate: "2026-02-26T00:00:00Z",
            effortEstimate: "8 hours",
          },
        ],
      },
    ],
  },
  {
    id: "proj-3",
    name: "Mobile App MVP",
    description:
      "Cross-platform mobile application for field team collaboration.",
    status: "Planning" as const,
    techStack: ["React Native", "Firebase", "Expo"],
    lastUpdated: "2026-02-20T14:00:00Z",
    features: [
      {
        id: "feat-9",
        name: "Offline Support",
        description: "Enable data sync when connectivity is limited.",
        priority: "High" as const,
        status: "To Do" as const,
        effortEstimate: "5 days",
        tasks: [
          {
            id: "task-19",
            title: "Set up local database",
            description: "Configure SQLite for offline storage",
            status: "To Do" as const,
            dueDate: "2026-03-01T00:00:00Z",
            effortEstimate: "1 day",
          },
          {
            id: "task-20",
            title: "Implement sync queue",
            description: "Queue changes for sync when online",
            status: "To Do" as const,
            dueDate: "2026-03-05T00:00:00Z",
            effortEstimate: "2 days",
          },
        ],
      },
      {
        id: "feat-10",
        name: "Push Notifications",
        description: "Real-time notifications for task updates.",
        priority: "Medium" as const,
        status: "To Do" as const,
        effortEstimate: "2 days",
        tasks: [
          {
            id: "task-21",
            title: "Configure Firebase Cloud Messaging",
            description: "Set up FCM for push notifications",
            status: "To Do" as const,
            dueDate: "2026-03-08T00:00:00Z",
            effortEstimate: "6 hours",
          },
        ],
      },
    ],
  },
  {
    id: "proj-4",
    name: "Analytics Dashboard",
    description: "Real-time analytics dashboard for business metrics.",
    status: "Archived" as const,
    techStack: ["Vue.js", "D3.js", "Python", "FastAPI"],
    lastUpdated: "2025-11-10T08:00:00Z",
    features: [
      {
        id: "feat-11",
        name: "Data Visualization",
        description: "Interactive charts and graphs for metrics.",
        priority: "High" as const,
        status: "Done" as const,
        effortEstimate: "4 days",
        tasks: [
          {
            id: "task-22",
            title: "Integrate D3.js charts",
            description: "Create custom visualizations",
            status: "Done" as const,
            dueDate: "2025-10-15T00:00:00Z",
            effortEstimate: "2 days",
          },
        ],
      },
    ],
  },
];

export const mockDecisions = [
  {
    id: "dec-1",
    date: "2026-01-15T10:00:00Z",
    text: "Use Next.js App Router for the e-commerce platform",
    pros: [
      "Server components improve performance",
      "Built-in routing and API capabilities",
      "Great developer experience with TypeScript",
    ],
    cons: [
      "Learning curve for App Router patterns",
      "Some third-party libraries need adaptation",
    ],
    alternatives:
      "Remix - similar full-stack capabilities\nTraditional SPA with separate backend",
    featureId: "feat-1",
  },
  {
    id: "dec-2",
    date: "2026-01-25T14:30:00Z",
    text: "Use PostgreSQL with Drizzle ORM for data persistence",
    pros: [
      "Type-safe database queries",
      "Lightweight and fast",
      "Great TypeScript support",
    ],
    cons: ["Less mature than Prisma", "Smaller community"],
    alternatives: "Prisma ORM\nraw SQL with node-postgres\nSupabase",
    featureId: "feat-2",
  },
  {
    id: "dec-3",
    date: "2026-02-01T09:00:00Z",
    text: "Implement shopping cart with React Context + LocalStorage",
    pros: [
      "Simple to implement and maintain",
      "Works offline without backend",
      "Familiar pattern for team",
    ],
    cons: ["No real-time sync across devices", "Limited to single browser"],
    alternatives:
      "Redux Toolkit with persistence\nServer state with React Query\nDatabase-backed cart",
    featureId: "feat-3",
  },
  {
    id: "dec-4",
    date: "2026-02-08T11:00:00Z",
    text: "Use shadcn/ui component library with Tailwind CSS",
    pros: [
      "Beautiful, accessible components",
      "Fully customizable via Tailwind",
      "Copy-paste approach gives full control",
    ],
    cons: ["Manual updates required", "More setup than ready-made UI kits"],
    alternatives: "Radix UI + custom styling\nMaterial UI\nChakra UI",
    featureId: "feat-5",
  },
  {
    id: "dec-5",
    date: "2026-02-12T16:00:00Z",
    text: "Implement search with command palette (Cmd+K) pattern",
    pros: [
      "Fast keyboard-driven access",
      "Industry-standard UX pattern",
      "Reduces navigation clicks",
    ],
    cons: ["Requires user education", "Mobile support challenging"],
    alternatives:
      "Traditional search bar in header\nElasticsearch-powered search page",
    featureId: "feat-8",
  },
  {
    id: "dec-6",
    date: "2026-02-18T13:00:00Z",
    text: "Store decisions as JSONB in PostgreSQL for flexibility",
    pros: [
      "Schema can evolve without migrations",
      "Rich data structures supported",
      "Good query performance",
    ],
    cons: [
      "Less validation than typed columns",
      "Harder to enforce constraints",
    ],
    alternatives:
      "Separate decisions table with normalized columns\nDocument store (MongoDB)",
    featureId: "feat-7",
  },
  {
    id: "dec-7",
    date: "2026-02-22T10:30:00Z",
    text: "Use Expo for React Native mobile app development",
    pros: [
      "Faster setup and development",
      "Easy builds for iOS/Android",
      "Good default configurations",
    ],
    cons: ["Some native modules require ejecting", "Larger app bundle size"],
    alternatives: "React Native CLI\nFlutter\nCapacitor + web app",
    featureId: "feat-9",
  },
];
